# Generated by Django 4.1.7 on 2024-07-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Time_allowed',
            field=models.DurationField(),
        ),
    ]
