# Generated by Django 4.1.7 on 2024-07-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_quiz_time_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Time_allowed',
            field=models.IntegerField(help_text='Enter duration in minutes'),
        ),
    ]
