# Generated by Django 4.1.7 on 2024-07-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_studentquizattempt_studentanswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentquizattempt',
            unique_together=set(),
        ),
    ]
