# Generated by Django 5.0.7 on 2024-07-22 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Quiz", "0001_initial"),
        ("Student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="assigned_to",
            field=models.ManyToManyField(to="Student.student"),
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Quiz.question"
            ),
        ),
        migrations.AddField(
            model_name="studentquizattempt",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Quiz.quiz"
            ),
        ),
        migrations.AddField(
            model_name="studentquizattempt",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Student.student"
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="Quiz.studentquizattempt",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentquizattempt",
            unique_together={("student", "quiz")},
        ),
    ]
