# Generated by Django 4.1.7 on 2024-07-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_user_is_user_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_student',
        ),
    ]
